# CUDA_LAUNCH_BLOCKING=1
# TORCH_CUDA_ARCH_LIST="9.0" CUDA_VISIBLE_DEVICES=0,1,2,3 MASTER_ADDR=localhost MASTER_PORT=12548 nsys profile -o test_multi_gpu_vanilla_%n python -u test_multi_gpu3.py
# CUDA_LAUNCH_BLOCKING=1 TORCH_USE_CUDA_DSA=1 CUDA_VISIBLE_DEVICES=4,5,6,7 MASTER_ADDR=localhost  MASTER_PORT=12548 python test_multi_gpu3.py
TORCH_CUDA_ARCH_LIST="9.0" CUDA_VISIBLE_DEVICES=0,1,2,3 MASTER_ADDR=localhost MASTER_PORT=12548 python test_multi_gpu3.py